### ISSUE TITLE
Issue with Node-RED 0.18.3 on IBM Cloud

### ISSUE THREAD

**Issue by emmajdaws** [seanmtracey/extract-keyframes#2]
Installing via Manage Palette on IBM Cloud doesn't work. When adding extract-keyframes in to Toolchain on IBM Cloud, it was causing a loop on the re-build and wouldn't run. I've forced Node-RED to 0.18.2 and it works.

Installing via Manage Palette works fine locally.

**Comment by seanmtracey** [comment]
Okie dokie, could you tell me a little more about the configuration of the system you're running Node-red on? Specifically, how much RAM is allocated to your machine?

**Comment by seanmtracey** [comment]
I've managed to install the node on `0.18.3` with 1Gb of memory. I have half a memory that I bumped it up from it's default when I first created the instance. I suspect a system running on less than 1gb of RAM can't handle the installation of the extract-keyframes dependencies. Going to dial down my existing instance to 512mb and reinstall to see if it can handle it.

**Comment by emmajdaws** [comment]
I think this may have been the issue. I was running it on the standard memory when the Node-RED instance is created. Having bumped up to 1 it did work, as you have experienced too.

**Comment by seanmtracey** [comment]
I've just tried to install the node on a 512 instance and it failed. I'm not able to get verbose debugging out of my instance, so I can't confirm that lack of memory is the absolute reason for failure, but I'm going to put a note on the module and recommend 1GB minimum RAM for installation until I have more time to nail it down + fix it.

**Comment by seanmtracey** [comment]
Just noticed this has also been logged on the Node-red module itself. I really need to actually watch my repos. Closing this issue to discuss it further over at the [Node-red repo.](https://github.com/seanmtracey/node-red-contrib-extract-keyframes/issues/2)
